### ISSUE TITLE
Using ```textureSample``` in an if statement will cause validation error

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/naga#1218]
Using ```textureSample``` in an if statement will cause validation error, I have tested it on the master branch of naga. 
As long as it is a dynamic if condition, it can be reproduced:
```
Entry point main at Fragment is invalid: 
        Required uniformity of control flow for IMPLICIT_LEVEL in [11] is not fulfilled because of Expression([6])
```
wgsl: 
```
...
[[group(0), binding(2)]] var bg_texture: texture_2d<f32>;
[[group(0), binding(3)]] var front_texture: texture_2d<f32>;
[[group(0), binding(4)]] var tex_sampler: sampler;

[[stage(fragment)]] 
fn main(in: VertexOutput) -> [[location(0)]] vec4<f32> {
    var frag_color: vec4<f32> = vec4<f32>(0.0);
    if (in.instance_index < 1u) {
        frag_color = textureSample(bg_texture, tex_sampler, in.paper_uv);
    }  else {
        frag_color = textureSample(front_texture, tex_sampler, in.brush_uv);
    }
    return frag_color;
}
```

**Comment by kvark** [comment]
This is by design (in WebGPU). Doing this in any of the shading languages results in one of the following:
  1) UB
  2) the shader compiler tries very hard to move the sampling and the associated logic out of the if condition. I don't think we can rely on this.

So WebGPU enforces this, thus avoiding UB. Your sampling instruction `textureSample` uses implicit LOD of the texture. Does it have mipmaps? If it doesn't, just use `textureSampleLevel` instead. if it does, you can get the gradients computed first (outside of the if/else), and then call `textureSampleGrad`. Finally, you can get both instructions in, and just `select()` the result based on the condition.

**Comment by kvark** [comment]
Hmm, where is "convert to discussion" button?

**Comment by cwfitzgerald** [comment]
@kvark discussions are disabled for naga
