### ISSUE TITLE
[msl-out] Immutability of nested pointer passing is incorrectly computed.

### ISSUE THREAD

**Issue by dragostis** [gfx-rs/naga#1262]
WGSL:

```wgsl
var<workgroup> val: u32;

fn foo_nested(p: ptr<workgroup, u32>, d: u32) {
    *p = *p + d;
}

fn foo(p: ptr<workgroup, u32>) {
    foo_nested(p, 42u);
}

[[stage(compute), workgroup_size(1)]]
fn main() {
    foo(&val);
}
```

Metal:

```metal
// language: metal1.1
#include <metal_stdlib>
#include <simd/simd.h>


void foo_nested(
    threadgroup metal::uint& p,
    metal::uint d
) {
    metal::uint _e3 = p;
    p = _e3 + d;
    return;
}

void foo(
    threadgroup metal::uint& p1
) {
    foo_nested(p1, 42u);
    return;
}

kernel void main1(
  threadgroup metal::uint const& val // THIS SHOULDN'T BE const
) {
    foo(val);
    return;
}
```

**Comment by kvark** [comment]
Thank you for filing this!
The problem is that our global usage tracking doesn't penetrate through pointer function arguments. We have two possible ways to proceed:
  1. implement a bunch of logic to track this across pointer boundaries. This is possible.
  2. don't implement anything until the `pointer` semantics is evolved in WGSL. AFAIK, it's supposed to be `pointer<class, T, access>`, in which case no tracking is needed. In the meantime, you can work around this by mutating the workgroup variable explicitly, e.g. `val = 0`;
