### ISSUE TITLE
[spv-out] SPIRV generation doesn't handle array-pointer-in-struct access.

### ISSUE THREAD

**Issue by dragostis** [gfx-rs/naga#1263]
WGLS:

```wgsl
struct Foo {
    bar: ptr<workgroup, array<u32, 32>>;
};

fn read_array_from_struct(foo: Foo, i: u32) -> u32 {
    return *(foo.bar[i]);
}

[[stage(compute), workgroup_size(1)]]
fn main() {

}
```

... gives following error in naga when convering to SPIR-V:

```
ERROR naga::back::spv::block] Unable to access base AccessIndex { base: [1], index: 0 } of type Pointer { base: [2], class: WorkGroup }
module is not validated properly: only vectors may be dynamically indexed by value
```
... caused in [src/back/spv/block.rs](https://github.com/gfx-rs/naga/blob/cefaa396d490024b19b31a2fcf9410d5d2b5bb2c/src/back/spv/block.rs#L278).

**Comment by kvark** [comment]
Thank you for filing all of these issues! Pointers are still relatively fresh in the spec, and our code needs improvement.

**Comment by JCapucho** [comment]
From https://gpuweb.github.io/gpuweb/wgsl/#struct-types
> A pointer, texture, or sampler must not appear in any level of nesting within an array or structure.

On master the validator catches this.

Also you would need to do:
```rust
return (*foo.bar)[i];
```
instead of
```rust
return *(foo.bar[i]);
```

Since indexing behind a pointer isn't allowed (so you use the `*` to get a reference to the array) and the returned value from indexing is a reference type (i.e. it gets auto loaded)
