### ISSUE TITLE
Naga complains of type error on spec example code

### ISSUE THREAD

**Issue by Matthew-Maclean** [gfx-rs/naga#1318]
This shader:
```
[[stage(compute), workgroup_size(1)]]
fn compute()
{
    var uv: vec2<f32>;
    uv.y = 1.25;      // Place 1.25 into the second component of uv.

    let uv_x_ptr: ptr<function,f32> = &uv.x;
    *uv_x_ptr = 2.5;   // Place 2.5 into the first component of uv.
}
```
Fails to compile on naga 0.6.0 with the type error:

```
[2021-09-02T04:23:09Z ERROR naga::front::wgsl] Given type Pointer { base: [2], class: Function } doesn't match expected ValuePointer { size: None, kind: Float, width: 4, class: Function }
error: the type of `uv_x_ptr` is expected to be [3]
  ┌─ wgsl:7:9
  │
7 │     let uv_x_ptr: ptr<function,f32> = &uv.x;
  │         ^^^^^^^^ definition of `uv_x_ptr`

Could not parse WGSL
```

Ignoring the fact that I don't know what `[3]` is supposed to be, this code as far as I am aware should compile, it's drawn from the working draft spec [here](https://www.w3.org/TR/WGSL/#assignment).

This seems like a pretty simple write into a pointer, and I really can't imagine why it wouldn't compile.

(as an aside, naga should support some kind of `--version` option, if only for debugging and issue reporting purposes.)

**Comment by kvark** [comment]
Some logic parts about pointers aren't polished/operational yet. E.g. #1322
The errors are cryptic until #358 is resolved.

**Comment by jimblandy** [comment]
> This seems like a pretty simple write into a pointer, and I really can't imagine why it wouldn't compile.

Yeah, totally.

The underlying issue here is that, for technical reasons, Naga IR actually has two different representations for some types. For example, a pointer to an `f32` could be:

```
[1] Scalar { kind: Float, width: 4 }
[2] Pointer { base: [1], class: C }
```

but this also supposed to be exactly equivalent:

```
[1] ValuePointer { size: None, kind: Float, width: 4, class: C }
```

The bug here is that [this comparison](https://github.com/gfx-rs/naga/blob/8aae069f22ac94ec46329a9adbfaf341cd3e7adf/src/front/wgsl/mod.rs#L3202) just uses exact equality on `TypeInner` to decide whether the assignment is okay, without putting the types in some canonical form first.

**Comment by jimblandy** [comment]
Filed #1382 for the remaining output problem.
