### ISSUE TITLE
[glsl-in] Shader rejected with "The expression ... may only be indexed by a constant"

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1343]
Tested using naga 7681f4a

[This shader](https://github.com/gfx-rs/naga/files/7144218/stable_bifurcation.json.frag.txt) is accepted by glslangValidator, but with naga it leads to a complaint about indexing via a non-constant. From the error message I couldn't work out which part of the shader is being complained about.

**Comment by JCapucho** [comment]
Thank you for filling a bug report, I've already opened a PR which fixes this issue, I do ask that next time you open a issue you try to provide a minimal test case, I know this is not always possible or easy but in those cases please at least make sure the shader is properly formatted, this is a small thing that adds confusion to the initial triaging and discourages working on the shader. 

Also if the shader is small (which is the case here) please inline it in the message it makes it easier to see what the issue is about at a glance.
