### ISSUE TITLE
Reporting naga SPIR-V input issues

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1569]
I have been using the SPIR-V front-ends of naga and tint as a way to generate interesting WGSL from fuzzed SPIR-V shaders.

In the process I have found quite a few SPIR-V examples that tint accepts but naga rejects (and vice versa).

Are the naga developers interested in me filing issues for (reduced) SPIR-V examples that look valid and that tint accepts but naga rejects?

**Comment by kvark** [comment]
Interesting question. What is the goal of your work?
One important thing to keep in mind is that Naga's SPV-in is *not* a validator, it's a translator. So it assumes the input SPIR-V is valid in the first place. If it's invalid, the main client of Naga - wgpu - doesn't really care, since it only cares about the validity of the product of the translation, not the source.

So if you found cases related to invalid SPIR-V in the first place, I don't think that's in scope for Naga to care about. If the SPIR-V are valid, then please file those bugs!

**Comment by afd** [comment]
The goal of the work is to fuzz Tint (to weed out crashes / vulnerabilities in the first instance).

The examples that Naga rejects are all valid SPIR-V, so I'll go ahead and file some bugs in due course - thanks.

BTW: the fuzzing techniques we're building for Tint should work equally well for Naga (though with Naga being written in Rust there's hopefully less scope for vulnerabilities than in C++), so if at some point you'd be interested in deploying them for Naga testing let me know and I can provide more info.

**Comment by kvark** [comment]
@jimblandy and I are definitely interested to get some fuzz. In fact, there is already something in https://github.com/gfx-rs/naga/tree/master/fuzz, but it needs to grow.
