### ISSUE TITLE
Use typifier in the backends

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#162]
Currently it's used in the frontends only, and it mutates the type arena.
GLSL and MSL backends would benefit from having this automated too, but we need to do something about the mutable arena.

**Comment by grovesNL** [comment]
Cross-posting from Matrix

Some compilers structure type queries/resolution similar to the following:
1. First frontends produce AST/IR with types that are declared directly (e.g. the type of `true` is known, and the type of `x` in `let x: A` is known). Little or no type resolution so most types are `None` at this point.
2. Then a type resolver/type checking pass resolves all types on the IR, and by the end of the pass every type must be known.
3. The fully-typed IR is passed to backends, and backends don't have to be concerned with deducing types (because everything is already known).

In Naga, I think steps 1 and 2 are currently combined, so there's not a separate pass to resolve all types. But maybe step 3 could still apply if we eagerly resolve all types during 1/2. In that case the backends could expect to work with fully typed IR.
