### ISSUE TITLE
[wgsl-out] Primary vs Secondary support (question)

### ISSUE THREAD

**Issue by markus-wa** [gfx-rs/naga#1705]
Hi there :slightly_smiling_face: 

I was wondering what the difference between primary and secondary support is (in the README).

A few things I was wondering:
- Does secondary support just mean there are known bugs?
- Are all conversions planned to eventually be fully (primarily) supported?
- May secondary support be dropped without much notice?
- Is runtime performance worse for secondary support?
- If this project doesn't provide primary support for wgsl-out, are there other projects that target wgsl-out (e.g. spirv-cross currently does not)

Of course if the answer is "eventually everything should have the same level of support" the other questions become irrelevant.

Thanks in advance!

Edit: for some background, I'm hoping to build an app with WebGPU that can take as input any (/as many as possible) shading languages

**Comment by kvark** [comment]
Hi!

Generally speaking, for me "primary support" means it's required by WebGPU and tested by WebGPU CTS.
Secondary support isn't possible to test with WebGPU CTS, so it's a best effort implementation and testing, generally driven by user requests and complaints. We have other test corpuses in place (like parsing Dota2 shaders), so the secondary support may very well be high quality, but it's not normative.

There are bugs in both primary and secondary support endpoints currently. We aren't planning on dropping any of them in the future.

Performance-wise, it's not trivial. On one hand, we strive to have the best performance in all endpoints. On the other hand, Naga's IR is very close to WGSL, which is designed by W3C working group. So any code paths in the primary endpoints are *designed* to be fast, whereas any other code paths aren't taken into account in the design. I'm not aware of any pitfalls in runtime performance right now that would be specific to secondary support endpoints.

> If this project doesn't provide primary support for wgsl-out, are there other projects that target wgsl-out (e.g. spirv-cross currently does not)

For Naga wgsl-out is very important, since it's a part of the WebGPU goal. It's also fairly straightforward, since, again, our IR is very close to WGSL. So I'm not worried about the quality of our results there.
You could also look at Tint - https://dawn.googlesource.com/tint/

**Comment by markus-wa** [comment]
thanks for the detailed answers @kvark 

that's pretty much what I hoped for on all fronts :smile: 

cheers!
