### ISSUE TITLE
[hlsl-out] error X4555: cannot use casts on l-values

### ISSUE THREAD

**Issue by hasali19** [gfx-rs/naga#1886]
I'm getting a really weird D3DCompile error with the following minimal test case:

```wgsl
struct MyStruct {
    a: i32,
    b: vec2<i32>,
}

struct Out {
    value: u32,
}

@group(0)
@binding(0)
var<storage, read_write> s_buf: Out;

fn my_fun() -> bool {
    var v = vec2<i32>(0);
    var s = MyStruct(0, v);
    var i = 0;

    loop {
        if (s_buf.value == (0u) || i > 2) {
            break;
        }
        s = MyStruct(i, v);
        i += 1;
    }

    return false;
}

@compute
@workgroup_size(1)
fn main() {
    s_buf.value = 0u;
    if (my_fun()) {
        s_buf.value = 1u;
    }
}
```

This fails with:

```
The application panicked (crashed).
Message:  wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
    Internal error: D3DCompile error (0x80004005): \\wsl.localhost\Ubuntu\home\hasan\dev\wgslsmith\Shader@0x000002751EC076D0(44,9): error X4555: cannot use casts on l-values
```

**Comment by teoxoy** [comment]
This might be an issue with FXC.
See https://shader-playground.timjones.io/9e70d834bf7fc6a1b10dbf1e43b8f327
DXC compiles the code just fine.

Not sure what we can do here...

**Comment by hasali19** [comment]
Is it possible to use wgpu with DXC instead?

**Comment by teoxoy** [comment]
I thought so but apparently not yet. @cwfitzgerald mentioned we might have a feature flag for it in wgpu in the future.

**Comment by amaiorano** [comment]
Hello, I work on Tint, and I took a look at this bug to see if we have a similar issue on our end. The problem here is that `ConstructMyStruct` doesn't initialize _all_ members of the struct -- that is, including the padding members. If you modify that function to do so, it works:

```
MyStruct ConstructMyStruct(int arg0, int2 arg1) {
    MyStruct ret;
    ret.a = arg0;
    ret._pad1_0 = 0; // Add this
    ret.b = arg1;
    return ret;
}
```
It would seem FXC sees this partially initialized struct as a different type, so the assignment of the return value to an existing l-value is seen a cast operation, which apparently isn't allowed.

So I guess for Naga, a workaround to make FXC happy is to emit initializers for padding members as well.

Note that we didn't reproduce this problem compiling the same shader in Tint because we don't use structs for storage buffers, so we don't add padding bytes to them. (We use arrays that we index out of for storage buffers).

**Comment by teoxoy** [comment]
@amaiorano thanks for the insight! Initializing the padding seems to fix the issue.

What is odd though is that in the link I shared above if you comment any of the 2 calls to `ConstructMyStruct` the code compiles but it doesn't with both calls.

Initializing the whole struct also solves the issue (the generated DXBC is identical compared to just initializing the padding).

```hlsl
MyStruct ConstructMyStruct(int arg0, int2 arg1) {
    MyStruct ret = (MyStruct)0;
    ret.a = arg0;
    ret.b = arg1;
    return ret;
}
```

We'll probably go with this since it doesn't require tracking of padding.

**Comment by amaiorano** [comment]
> What is odd though is that in the link I shared above if you comment any of the 2 calls to ConstructMyStruct the code compiles but it doesn't with both calls.

Having implemented many workarounds for FXC in Tint, I can't say I'm that surprised. FXC is full of bugs, many around flow control analysis. This is probably one of them, as one of the calls is in a loop with a conditional break above it. If I had to venture a guess, I would say that when you comment out one of the calls, FXC optimizes the `s` variable so that it's no longer an l-value that gets overwritten, but simply one that gets initialized once, so we no longer get this error.
