### ISSUE TITLE
[glsl-in] Unknown function 'findMSB'

### ISSUE THREAD

**Issue by hanawatson** [gfx-rs/naga#1946]
naga glsl-in is rejecting the `findMSB` function when it is wrapped around one of several other functions including `abs`, `ceil`, `exp`, `exp2`, `floor`, `fract`, `inversesqrt` etc. (seems to be all unary mathematical operations so far). It accepts literals, but not e.g. binary expressions.

GLSL (also applies for 450 core):
```
#version 440 core
#extension GL_ARB_compute_shader : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint var0_ = findMSB(abs(0u));
}
```

Error:
```
error: Unknown function 'findMSB'
  ┌─ temptest.comp:6:18
  │
6 │     uint var0_ = findMSB(abs(0u));
  │                  ^^^^^^^^^^^^^^^^
```

Edit: this is also happening with `findLSB` and possibly `bitfieldInsert`.

**Comment by JCapucho** [comment]
This is normal, using `glslang` will give you the same result, this is because all the inner functions you define don't accept unsigned ints only signed, so a implicit conversion is performed, problem is that glsl defines that implicit conversions to floats are preferred to ints, so you get essentially
```glsl
findMSB(abs(float(0u)))
```
`findMSB` isn't implemented for floats
