### ISSUE TITLE
[glsl-in] Use &str instead of String for token values

### ISSUE THREAD

**Issue by pjoe** [gfx-rs/naga#231]
From https://github.com/gfx-rs/naga/pull/227#discussion_r500300698

To avoid excessive allocations, the token values should use `&str` instead of `String`.

This affects both lexer and parser.

**Comment by JCapucho** [comment]
With the new lexer I fear this is not possible, this issue is inherent of the preprocessor spec itself and not the implementation, a token provided to the parser will have suffered a lot of modifications from the source and as such it needs to be a `String`, so I'll be closing this and if anyone wants to fix or talk about this issue the discussion should be made in https://github.com/Kangz/glslpp-rs since it's the part responsible for the token generation.
