### ISSUE TITLE
Artifacts when using binding_array with textures. #2282 Related

### ISSUE THREAD

**Issue by trixnz** [gfx-rs/naga#2408]
I originally created an issue on https://github.com/bevyengine/bevy/issues/9221 as that was where I first noticed the behaviour, but curiosity got the better of me, so while bisecting through naga and running the [texture-arrays](https://github.com/gfx-rs/wgpu/blob/trunk/examples/texture-arrays) example each step, I found that this https://github.com/gfx-rs/wgpu/commit/dcad7dfb commit resulted in the artifacts appearing. 

Okay, so it's in naga; more bisecting through naga and this commit https://github.com/gfx-rs/naga/commit/37b3c36a8f1aaa611e0dcfc4892333e83ac3a919 introduces the behaviour.

## Relevant system information:
OS: `NixOS 23.11.20230719.7f256d7 (Tapir)`
Display Server: `Wayland 1.22`
```ignore
AdapterInfo { name: "AMD Radeon RX 6800 XT (RADV NAVI21)", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.1.3", backend: Vulkan } 
```

From what I can visibly observe, it seems like textures from other indices in the array are bleeding over into other textures. The artifact colors are *always* from another texture in the array.

I've attached a screenshot:
![image](https://github.com/gfx-rs/naga/assets/2995953/1f753a79-d6f3-4b33-92e6-2cf65ee1a478)
*Artifacts in the image, more prominent when resizing the window*

If there's any additional information I can provide to help track down the cause, i'm more than happy to pass it on!

**Comment by cwfitzgerald** [comment]
Very nice! I actually noticed this myself, I just forgot to file. This only affects AMD as only AMD cares, but how we are setting the NON_UNIFORM flag in spirv isn't correct.

**Comment by kvark** [comment]
What exactly is wrong with our non-uniform declarations? Does the [test output](https://github.com/gfx-rs/naga/blob/535701f6b2f38f7e0088701ee4cf6d8024f74a21/tests/out/spv/binding-arrays.spvasm) has the issue?

**Comment by cwfitzgerald** [comment]
If you run that spirv through spirv-cross (or do as I have and run wgsl through rga) you'll see that neither pick up the image accesses as non-uniform and generate the appropriate code. I suspect it's because we're marking the result of the access chain non-uniform as opposed to the resulting OpLoad - but we should compare with what glslc generates.

**Comment by cwfitzgerald** [comment]
Yeah just validated this with the example if you do the following as is:

```
spirv-as ./tests/out/spv/binding-array.spvasm -o binding-array.spv
spirv-cross binding-array.spv -V
```

you get:

```glsl
    if (all(lessThan(uvec2(_120), uvec2(imageSize(_12[_116])))))
    {
        imageStore(_12[_116], _120, _107);
    }
```

at the end of the shader.

If you change https://github.com/gfx-rs/naga/blob/535701f6b2f38f7e0088701ee4cf6d8024f74a21/tests/out/spv/binding-arrays.spvasm#L59 to point at 413 (the load result) instead of 412 (the access chain result) and run the same commands, you get

```glsl
     if (all(lessThan(uvec2(_120), uvec2(imageSize(_12[nonuniformEXT(_116)])))))
    {
        imageStore(_12[nonuniformEXT(_116)], _120, _107);
    }
```

**Comment by cwfitzgerald** [comment]
I don't think this will be that hard to fix, will try it tomorrow.
