### ISSUE TITLE
[msl] Refactor MaybeOwned

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#29]
It was introduced when the types weren't copyable. Now they are. Maybe we can simplify this better.

**Comment by paulkernfeld** [comment]
I would be interested in trying this out. It looks to me like `MaybeOwned` is being used with `TypeInner`, which currently can't be `Copy` because the `Struct` variant contains a `Vec`. Do we need to modify the `Struct` variant so that it can be `Copy`? Or, maybe I'm misunderstanding the nature of the proposed refactor?

**Comment by kvark** [comment]
Hah, good point! I suppose we still need to use `MaybeOwned` then. Going to close this for now.
